server:
  port: 9001
spring:
  application:
    name: base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.128:3306/tensquare_base?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.20.128